resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

description 'ESX Supermarket'

version '1.0.1'

files {
	'html/ui.html',
	'html/styles.css',
	'html/scripts.js',
	'html/debounce.min.js',
	'html/iransans.otf',
	'html/GoodBrush.ttf',
	
	'html/img/bread.png',
	'html/img/fixkit.png',
	'html/img/soda.png',
    'html/img/ticket.png',
	'html/img/banana.png',
	'html/img/orange.png',
	'html/img/donut.png',
	'html/img/fixkit.png',
	'html/img/energy.png',
	'html/img/jusfruit.png',
	'html/img/close.png',
	'html/img/croquettes.png',
	'html/img/water.png',
    'html/img/contract.png',
	'html/img/plus.png',
	'html/img/tabacblond.png',
    'html/img/raisin.png',
    'html/img/tabacbrun.png',
    'html/img/tabacblondsec.png',
    'html/img/tabacbrunsec.png',
    'html/img/malbora.png',
    'html/img/gitanes.png',
    'html/img/soda.png',
    'html/img/cappuccino.png',
    'html/img/beer.png',
    'html/img/drill.png',
    'html/img/teqpaf.png',
    'html/img/viande.png',
    'html/img/viande_meat.png',
    'html/img/jager.png',
    'html/img/ice.png',
    'html/img/fishingrod.png',
    'html/img/grapperaisin.png',
    'html/img/turtle_meat.png',
    'html/img/turtle.png',
    'html/img/hamburger2.png',
    'html/img/grand_cru.png',
    'html/img/bag.png',
    'html/img/vine.png',
    'html/img/menu.png',
    'html/img/binoculars.png',
    'html/img/pain.png',
    'html/img/cannabis.png',
    'html/img/cigarette.png',
    'html/img/clip.png',
    'html/img/cocacola.png',
    'html/img/coffee.png',
    'html/img/coke.png',
    'html/img/coke_pooch.png',
    'html/img/meth.png',
    'html/img/meth_pooch.png',
    'html/img/opium.png',
    'html/img/opium_pooch.png',
    'html/img/weed.png',
    'html/img/gold.png',
    'html/img/patate.png',
    'html/img/fixtool.png',
    'html/img/carotool.png',
    'html/img/mixapero.png',
    'html/img/metreshooter.png',
    'html/img/icetea.png',
    'html/img/martini.png',
    'html/img/sandwich.png',
    'html/img/papers.png',
    'html/img/hamburger.png',
    'html/img/wine.png',
    'html/img/cash.png',
    'html/img/chocolate.png',
    'html/img/carokit.png',
    'html/img/jus_raisin.png',
    'html/img/jusfruit.png',
    'html/img/menthe.png',
    'html/img/iron.png',
    'html/img/jewels.png',
    'html/img/cocktail.png',
    'html/img/blowpipe.png',
    'html/img/gazbottle.png',
    'html/img/contrat.png',
    'html/img/work_pay.png',
    'html/img/radio.png',
    'html/img/medikit.png',
    'html/img/saucisson.png',
    'html/img/blackberry.png',
    'html/img/tequila.png',
    'html/img/whisky.png',
    'html/img/limonade.png',
    'html/img/phone.png',
    'html/img/vodka.png',
    'html/img/eau.png',
    'html/img/cupcake.png',
    'html/img/drpepper.png',
    'html/img/energy.png',
    'html/img/croquettes.png',
    'html/img/bolpistache.png',
    'html/img/bolnoixcajou.png',
    'html/img/bolcacahuetes.png',
    'html/img/fixkit.png',
    'html/img/bolchips.png',
    'html/img/black_chip.png',
    'html/img/black_money.png',
    'html/img/gym_membership.png',
	'html/img/minus.png'
}

ui_page 'html/ui.html'

client_scripts {
	'@es_extended/locale.lua',
	'locales/de.lua',
	'locales/br.lua',
	'locales/en.lua',
	'locales/fi.lua',
	'locales/fr.lua',
	'locales/es.lua',
	'locales/sv.lua',
	'locales/pl.lua',
	'locales/fa.lua',
	'config.lua',
	'client/main.lua'
}

server_scripts {
	'@es_extended/locale.lua',
	'@mysql-async/lib/MySQL.lua',
	'locales/de.lua',
	'locales/br.lua',
	'locales/en.lua',
	'locales/fi.lua',
	'locales/fr.lua',
	'locales/es.lua',
	'locales/sv.lua',
	'locales/pl.lua',
	'locales/fa.lua',
	'config.lua',
	'server/main.lua'
}

dependency 'es_extended'
